---
- hosts: master,slave1,slave2,chat1,chat2
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: Add repository to yum.repos.d
    yum: state=present name="http://repo.mysql.com/yum/mysql-5.6-community/el/7/x86_64/mysql-community-release-el7-5.noarch.rpm"
  - name: install mysql-server
    yum: name="mysql-community-server" state=latest
  - name: copy configs for mysql servers
    template: src="{{ HOST }}/{{ item }}.cnf" dest=/etc/my.cnf.d/
    with_items:
        - 01-basics
        - 02-binlog
  - name: enable new configs
    shell: |
        echo "!includedir /etc/my.cnf.d" >> /etc/my.cnf
  - name: copy start script
    template: src="{{ HOST }}/script.sql.j2" dest=/var/lib/mysql/.script.sql
  - name: start mysqld
    systemd: service=mysqld enabled=yes state=restarted
  - name: Copy monitoring script
    copy: src="monitor.sh" dest="/home/vagrant/monitor.sh"

- hosts: master,chat1,chat2
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: create database, load dump to it and dump from it with needed tables
    shell: |
        cat /var/lib/mysql/.script.sql | mysql -uroot
        rm /var/lib/mysql/.script.sql

- hosts: slave1,slave2,slave3,slave4
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: load master dump and start slave
    shell: |
        mysqldump -h '{{ MASTER_HOST }}' -u'{{ REPL_USER }}' -p'{{ REPL_PASS }}' '{{ DB_NAME }}' > /tmp/social.dump.sql
        cat /var/lib/mysql/.script.sql | mysql -uroot

- hosts: redis,rabbitmq,tarantool
  become: true
  tasks:
  - name: install epel-release
    yum: state=latest name=epel-release

- hosts: redis
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: install redis
    yum: state=latest name=redis
  - name: replace bind address for redis
    shell: |
        sed -i 's/^bind 127.0.0.1/bind 0.0.0.0/g' /etc/redis.conf
  - name: start redis
    systemd: service=redis enabled=yes state=restarted

- hosts: rabbitmq
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: install rabbitmq-server
    yum: state=latest name=rabbitmq-server
  - name: start rabbitmq-server
    systemd: service=rabbitmq-server enabled=yes state=restarted

- hosts: tarantool
  vars_files:
    - vars.yml
  become: true
  tasks:
  - name: copy tarantool repo
    copy: src="tarantool.repo" dest="/etc/yum.repos.d/tarantool_1_10.repo"
  - name: install tarantool
    yum: state=latest name=tarantool
