HOME = ENV['OTUS_VAGRANT_HOME']

MACHINES = {
    "master": {
        :box_name => "centos/7",
        :net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.1",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "master",
        :ID => 1,
    },
    "slave1": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.2",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "slave",
        :ID => 2,
    },
    "slave2": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.3",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "slave",
        :ID => 3,
    },
    "chat1": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.4",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "master",
        :ID => 4,
    },
    "chat2": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.5",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "master",
        :ID => 5,
    },
    "redis": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.6",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "redis",
        :ID => 6,
    },
    "rabbitmq": {
        :box_name => "centos/7",
		:net => [
            {
                virtualbox__intnet: "db-net",
                adapter: 2,
                ip: "10.10.0.7",
                netmask: "255.255.255.240",
            },
        ],
        :HOST => "rabbitmq",
        :ID => 7,
    },
}


Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.box_version = boxconfig[:box_version]

            __boxname = boxname.to_s
            box.vm.host_name = __boxname

            if __boxname.match(/master/) || __boxname.match(/slave\d/) || __boxname.match(/chat\d/)
              box.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true
              box.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
            elsif __boxname.match(/redis/)
              box.vm.network "forwarded_port", guest: 6379, host: 6379, auto_correct: true
            elsif __boxname.match(/rabbitmq/)
              box.vm.network "forwarded_port", guest: 5672, host: 5672, auto_correct: true
            end

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
                vb.customize ["modifyvm", :id, "--cpus", 1]
            end

			box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
                [ -e /tmp/id_rsa ] && mv /tmp/id_rsa ~root/.ssh
                echo "alias vim=vi" >> /etc/bashrc
            SHELL

            box.vm.provision "ansible" do |ansible|
                ansible.playbook = "provisioning/playbook.yml"
                ansible.extra_vars = MACHINES[boxname]
                ansible.verbose = 'vv'
            end

        end
    end
end
